# Generated by Django 4.2.4 on 2023-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=50, unique=True)),
                ("body", models.TextField(max_length=1000)),
                (
                    "cover_image",
                    models.ImageField(default="default.jpg", upload_to="about_us"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50, unique=True)),
                (
                    "cover_image",
                    models.ImageField(default="default.jpg", upload_to="covers"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=500)),
                (
                    "cover_image",
                    models.ImageField(default="default.jpg", upload_to="products"),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UpcomingEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=100, null=True)),
                ("date", models.CharField(max_length=100, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        default="default.jpg", upload_to="upcoming_events"
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
    ]
