# Generated by Django 4.2.4 on 2023-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutus",
            old_name="body",
            new_name="body1",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="body2",
            field=models.TextField(default="default", max_length=1000),
            preserve_default=False,
        ),
    ]
